### ISSUE TITLE
Information missing on how to connect using mobile with SAML authentication

### ISSUE THREAD

**Issue by strawhat5** [awsdocs/aws-client-vpn-user-guide#2]
Please add details on how to use it with mobile, **in case of SAML authentication**.

For mutual auth based `opvn` config, we can connect it using OpenVPN Android/iOS app. But how does it work in case we want to use it for federated-auth (like SAML based authentication). For **federated-auth connection**, we use [AWS VPN client](https://aws.amazon.com/vpn/client-vpn-download/) for Desktop connection. Is there something similar for Android/iOS?

@jpeddicord @katerini

**Comment by gumdelli** [comment]
@katerini @jpeddicord are there any updates on this? There is no documentation for using the AWS VPN on Android/iOS

**Comment by eXeDK** [comment]
Anything new on this? The official OpenVPN Connect app does not seem to support federated SAML authentication.

**Comment by ekanai** [comment]
I faced same issue.

**Comment by eXeDK** [comment]
@julieso do you know who can help with this?

**Comment by oskariin7** [comment]
Facing here the same problem. I'm currently using a mutual authentication endpoint for android devices, but it would be great to have support on android/iOS for SAML auth too!

**Comment by volodymyrrudyi** [comment]
The same. We can't test our mobile apps because of this.

**Comment by twixr** [comment]
Same issue. Docs are incomplete, does not work with AWS SSO

**Comment by antonxo** [comment]
The same issue. If I want to connect from a mobile device, I have to use certificates based (mutual) auth and give up user-based auth and its features.

**Comment by paulocesar-ufu** [comment]
Same here

**Comment by erbesharat** [comment]
It's been a year since this issue has been created, any updates?

**Comment by ghost** [comment]
Thank you for bringing this to our attention.  

In the Client VPN User Guide (connect.md) there is a note stating "For SAML-based federated authentication, you must use the AWS provided client to connect to a Client VPN endpoint." 

Since the AWS provided client is not available for mobile devices, SAML-based federated authentication for mobile devices is not supported at this time.  

I'll add this info to the team's list of items for future consideration and then close this issue.

**Comment by Nimdy** [comment]
Needs community pressure to add phone application support

**Comment by antonxo** [comment]
I've just recently chosen plain OpenVPN over AWS ClientVPN because the latter doesn't support federated login on mobile. AWS is losing potential income.
