### ISSUE TITLE
The Linux Ubuntu VPN client app is missing private DNS resolution support

### ISSUE THREAD

**Issue by dimisjim** [awsdocs/aws-client-vpn-user-guide#3]
what the title says, version 1.0.0 released earlier this month:

![image](https://user-images.githubusercontent.com/6890249/123236724-57278200-d4dd-11eb-8c8f-e067cd275087.png)

**Comment by project0** [comment]
@dimisjim did you checked the troubleshooting guide? It might be a problem with missing or wrongly configured systemd-resolved. https://docs.aws.amazon.com/vpn/latest/clientvpn-user/linux-troubleshooting.html#aws-provided-client

**Comment by dimisjim** [comment]
No, but will try
